#! /bin/bash
#
# Build streamOutApp against the shared GStreamer sysroot.
#
# Usage:
#   ./build_android.sh                    # assembleDebug (default)
#   ./build_android.sh release            # assembleRelease
#   ./build_android.sh debug clean        # wipe app/build + app/.cxx + app/src/main/libs first
#   ./build_android.sh clean              # clean only, no build
#
# Prereqs:
#   1. platforms/android/scripts/install_sdk_ndk.sh has been run (SDK/NDK
#      installed under the paths env.sh points to).
#   2. platforms/android/scripts/build_gstreamer.sh has been run
#      (populates $GSTREAMER_SYSROOT).
#
# Notes:
#   - This script sources the shared Android env (env.sh) to get SDK/NDK
#     locations, CERBERO_BRANCH, GSTREAMER_SYSROOT, etc.  If per-ABI env
#     files are ever added (env_arm64-v8a.sh, env_armeabi-v7a.sh), swap
#     the `ENV_SH` assignment below.
#   - local.properties is rewritten from the sourced env so the Android
#     Gradle Plugin uses the same SDK/NDK that env.sh selected.

set -euo pipefail

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
ABI="arm64-v8a"          # only ABI our GStreamer sysroot supports
BUILD_TYPE="debug"
DO_CLEAN=0
BUILD_ONLY_CLEAN=0

for arg in "$@"; do
    case "$arg" in
        debug|release) BUILD_TYPE="$arg" ;;
        clean)         DO_CLEAN=1 ;;
        clean-only)    DO_CLEAN=1; BUILD_ONLY_CLEAN=1 ;;
        *) echo "Unknown arg: $arg (expected: debug|release|clean|clean-only)"; exit 2 ;;
    esac
done

# If the user only passed 'clean' with no build type, treat as clean-only.
if [ $# -eq 1 ] && [ "$1" = "clean" ]; then
    BUILD_ONLY_CLEAN=1
fi

# ---------------------------------------------------------------------------
# Shared Android env
# ---------------------------------------------------------------------------
# When per-ABI env files land, use:
#   ENV_SH="$HOME/shared/platforms/android/env_${ABI}.sh"
ENV_SH="$HOME/shared/platforms/android/env.sh"

if [ ! -f "$ENV_SH" ]; then
    echo "ERROR: shared Android env not found at $ENV_SH" >&2
    exit 1
fi
# shellcheck disable=SC1090
. "$ENV_SH"

: "${ANDROID_HOME:?ANDROID_HOME not set by $ENV_SH}"
: "${ANDROID_NDK_HOME:?ANDROID_NDK_HOME not set by $ENV_SH}"
: "${GSTREAMER_SYSROOT:?GSTREAMER_SYSROOT not set by $ENV_SH}"

if [ ! -d "$GSTREAMER_SYSROOT/share/gst-android/ndk-build" ]; then
    cat >&2 <<EOF
ERROR: GSTREAMER_SYSROOT does not look like a valid cerbero dist:
       $GSTREAMER_SYSROOT
       (missing share/gst-android/ndk-build)

       Run the shared GStreamer build first:
           bash $HOME/shared/platforms/android/scripts/build_gstreamer.sh
EOF
    exit 1
fi

# ---------------------------------------------------------------------------
# Move to project root, sync local.properties from env
# ---------------------------------------------------------------------------
cd "$(dirname "$(readlink -f "$0")")"

cat > local.properties <<EOF
# Auto-generated by build_android.sh from $ENV_SH -- do not hand-edit.
# Only sdk.dir is set; the NDK is located via android.ndkVersion in
# app/build.gradle (AGP then finds \$ANDROID_HOME/ndk/<ndkVersion>).
# Writing ndk.dir here would trigger AGP's [CXX5106] deprecation warning.
sdk.dir=$ANDROID_HOME
EOF

echo "==> streamOutApp"
echo "    ABI               = $ABI"
echo "    ANDROID_HOME      = $ANDROID_HOME"
echo "    ANDROID_NDK_HOME  = $ANDROID_NDK_HOME"
echo "    GSTREAMER_SYSROOT = $GSTREAMER_SYSROOT"
echo "    CERBERO_BRANCH    = ${CERBERO_BRANCH:-<unset>}"

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------
if [ "$DO_CLEAN" = "1" ]; then
    echo "==> Cleaning app/build, app/.cxx, app/src/main/libs"
    ./gradlew clean
    rm -rf app/build app/.cxx app/src/main/libs app/src/main/obj
    if [ "$BUILD_ONLY_CLEAN" = "1" ]; then
        echo "Clean complete."
        exit 0
    fi
fi

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
# Title-case the build type: debug -> Debug, release -> Release
TASK="assemble${BUILD_TYPE^}"

echo "==> ./gradlew --stacktrace $TASK"
./gradlew --stacktrace "$TASK"

APK="app/build/outputs/apk/${BUILD_TYPE}/app-${BUILD_TYPE}.apk"
if [ -f "$APK" ]; then
    echo "==> APK: $(readlink -f "$APK")"
fi
