#!/usr/bin/env bash
#
# Step 2: install the Android SDK command-line tools and the specific
# platform, build-tools, NDK and CMake versions this project needs.
#
# Idempotent: safe to re-run. If a component is already installed at the
# pinned version, sdkmanager is a no-op.
#
# Consumes: env.sh at the repository root (versions + install paths).
# Produces: a populated $ANDROID_HOME and an updated shared env file at
#           $SHARED_ANDROID_ENV_FILE (default $HOME/shared/platforms/android/env.sh)
#           so the unchanged build_android.sh can source it.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate repo root and source env.sh
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

if [ ! -f "$REPO_ROOT/env.sh" ]; then
    echo "ERROR: $REPO_ROOT/env.sh not found. Create it from the template first." >&2
    exit 1
fi
# shellcheck disable=SC1091
. "$REPO_ROOT/env.sh"

: "${ANDROID_HOME:?env.sh must export ANDROID_HOME}"
: "${ANDROID_API_LEVEL:?env.sh must export ANDROID_API_LEVEL}"
: "${ANDROID_BUILD_TOOLS:?env.sh must export ANDROID_BUILD_TOOLS}"
: "${ANDROID_NDK_VERSION:?env.sh must export ANDROID_NDK_VERSION}"
: "${ANDROID_CMAKE_VERSION:?env.sh must export ANDROID_CMAKE_VERSION}"
: "${ANDROID_CMDLINE_TOOLS_VERSION:?env.sh must export ANDROID_CMDLINE_TOOLS_VERSION}"

echo "==> install_sdk_ndk.sh"
echo "    ANDROID_HOME          = $ANDROID_HOME"
echo "    ANDROID_API_LEVEL     = $ANDROID_API_LEVEL"
echo "    ANDROID_BUILD_TOOLS   = $ANDROID_BUILD_TOOLS"
echo "    ANDROID_NDK_VERSION   = $ANDROID_NDK_VERSION"
echo "    ANDROID_CMAKE_VERSION = $ANDROID_CMAKE_VERSION"

mkdir -p "$ANDROID_HOME"

# ---------------------------------------------------------------------------
# Install / refresh cmdline-tools under $ANDROID_HOME/cmdline-tools/latest
# ---------------------------------------------------------------------------
CMDLINE_DIR="$ANDROID_HOME/cmdline-tools/latest"
SDKMANAGER="$CMDLINE_DIR/bin/sdkmanager"

if [ ! -x "$SDKMANAGER" ]; then
    echo "==> Installing Android command-line tools ($ANDROID_CMDLINE_TOOLS_VERSION)"
    TMP_ZIP="$(mktemp --suffix=.zip)"
    trap 'rm -f "$TMP_ZIP"' EXIT

    curl -fSL \
        "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_CMDLINE_TOOLS_VERSION}_latest.zip" \
        -o "$TMP_ZIP"

    STAGE="$(mktemp -d)"
    unzip -q "$TMP_ZIP" -d "$STAGE"

    mkdir -p "$ANDROID_HOME/cmdline-tools"
    rm -rf "$CMDLINE_DIR"
    mv "$STAGE/cmdline-tools" "$CMDLINE_DIR"
    rm -rf "$STAGE"
fi

# ---------------------------------------------------------------------------
# Accept licenses + install pinned packages
# ---------------------------------------------------------------------------
export ANDROID_SDK_ROOT="$ANDROID_HOME"

echo "==> Accepting SDK licenses"
# NB: `yes | sdkmanager --licenses` is unsafe under `set -o pipefail`.
# sdkmanager closes stdin after reading a bounded number of prompts, `yes`
# then dies with SIGPIPE (exit 141), and pipefail aborts the whole script
# silently before the install step runs. Feed a bounded stream instead.
printf 'y\n%.0s' $(seq 1 100) | "$SDKMANAGER" --sdk_root="$ANDROID_HOME" --licenses >/dev/null

echo "==> Installing SDK components"
"$SDKMANAGER" --sdk_root="$ANDROID_HOME" \
    "platform-tools" \
    "platforms;android-${ANDROID_API_LEVEL}" \
    "build-tools;${ANDROID_BUILD_TOOLS}" \
    "ndk;${ANDROID_NDK_VERSION}" \
    "cmake;${ANDROID_CMAKE_VERSION}"

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
test -d "$ANDROID_HOME/platforms/android-${ANDROID_API_LEVEL}" \
    || { echo "ERROR: platform android-${ANDROID_API_LEVEL} missing" >&2; exit 1; }
test -d "$ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}" \
    || { echo "ERROR: NDK ${ANDROID_NDK_VERSION} missing" >&2; exit 1; }
test -d "$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS}" \
    || { echo "ERROR: build-tools ${ANDROID_BUILD_TOOLS} missing" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Write the shared env file consumed by build_android.sh
# ---------------------------------------------------------------------------
# build_gstreamer.sh will rewrite this with GSTREAMER_SYSROOT populated.
# Writing a partial file here means an accidental early `./build_android.sh`
# still gives a clear "GSTREAMER_SYSROOT not set" error rather than a
# missing-file error.
mkdir -p "$SHARED_ANDROID_ENV_DIR"
cat > "$SHARED_ANDROID_ENV_FILE" <<EOF
# Auto-generated by platforms/android/scripts/install_sdk_ndk.sh -- do not edit.
export ANDROID_HOME="$ANDROID_HOME"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/$ANDROID_NDK_VERSION"
export GSTREAMER_SYSROOT="${GSTREAMER_SYSROOT:-}"
export CERBERO_BRANCH="$CERBERO_BRANCH"
EOF

echo "==> Wrote $SHARED_ANDROID_ENV_FILE"
echo "==> SDK/NDK install complete."
